services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: ms_redis
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5132:5432"
    volumes:
      - ms_redis_data:/var/lib/postgresql/data

volumes:
  ms_redis_data:
