--  NOTA: Por defecto, hibernate esta configurado en ddl-auto update,
--  por lo que no es necesario ejecutar este script, ya que se encargara
--  de crear las tablas en la base de datos automáticamente.

CREATE TABLE public.persona (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	direccion varchar(255) NOT NULL,
	edad int4 NOT NULL,
	genero varchar(255) NOT NULL,
	identificacion varchar(255) NOT NULL,
	nombre varchar(255) NOT NULL,
	telefono varchar(255) NOT NULL,
	CONSTRAINT persona_genero_check CHECK (((genero)::text = ANY ((ARRAY['MALE'::character varying, 'FEMALE'::character varying, 'OTHER'::character varying])::text[]))),
	CONSTRAINT persona_pkey PRIMARY KEY (id),
	CONSTRAINT ukr5vsms84ih2viwd6tatk9o5pq UNIQUE (identificacion)
);


CREATE TABLE public.cliente (
	estado bool NOT NULL,
	contrasena varchar(255) NOT NULL,
	clienteid int8 NOT NULL,
	CONSTRAINT cliente_pkey PRIMARY KEY (clienteid),
	CONSTRAINT fkltuad7gvir4i2nu5wse9mnb8 FOREIGN KEY (clienteid) REFERENCES public.persona(id)
);

CREATE TABLE public.cuenta (
	numero_cuenta varchar(255) NOT NULL,
	estado bool NOT NULL,
	saldo numeric(38, 2) NOT NULL,
	tipo_cuenta varchar(255) NOT NULL,
	id_cliente int8 NOT NULL,
	CONSTRAINT cuenta_pkey PRIMARY KEY (numero_cuenta),
	CONSTRAINT cuenta_tipo_cuenta_check CHECK (((tipo_cuenta)::text = ANY ((ARRAY['CORRIENTE'::character varying, 'AHORROS'::character varying])::text[]))),
	CONSTRAINT fkmkmi3xf6wrp0y1mdn8nm4weim FOREIGN KEY (id_cliente) REFERENCES public.cliente(clienteid)
);


CREATE TABLE public.movimiento (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	descripcion varchar(255) NOT NULL,
	fecha timestamptz(6) NOT NULL,
	monto numeric(38, 2) NOT NULL,
	saldo_inicial numeric(38, 2) NOT NULL,
	numero_cuenta varchar(255) NOT NULL,
	CONSTRAINT movimiento_pkey PRIMARY KEY (id),
	CONSTRAINT fkk10u787s9re28fue9gdscb5kt FOREIGN KEY (numero_cuenta) REFERENCES public.cuenta(numero_cuenta)
);
